feat: update netcdf4-python to 1.6.5

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -12,24 +12,15 @@ export HDF5_LIBDIR=/usr/lib/$(DEB_HOST_MULTIARCH)/hdf5/serial
 
 export USE_NCCONFIG=1
 
+export PYBUILD_TEST_CUSTOM=1
+export PYBUILD_TEST_ARGS=cd test && NO_NET=1 NO_PLUGINS=1 {interpreter} run_all.py
+
 %:
-	dh $@ \
-	  --with python3 \
-	  --buildsystem=pybuild
+	dh $@ --buildsystem=pybuild
 
 override_dh_auto_test:
-	PYBUILD_SYSTEM=custom \
-	PYBUILD_TEST_ARGS="cd test && NO_NET=1 {interpreter} run_all.py" dh_auto_test || echo "Ignoring test failures"
-
-override_dh_auto_install:
-	dh_auto_install
-
-	# removing embedded rpath in libraries
-	-find $(CURDIR)/debian/*/usr/lib -name "*.so*" -type f -exec chrpath --delete {} \;
-
-override_dh_install:
-	dh_install --list-missing
-
-override_dh_python3:
-	dh_python3 -ppython3-netcdf4
-	dh_numpy3 -ppython3-netcdf4
+ifneq (,$(filter $(DEB_BUILD_ARCH),s390x hppa powerpc ppc64 sparc64))
+	dh_auto_test || echo "Ignoring test failures"
+else
+	dh_auto_test
+endif
